/*
 * jz4760ost.h
 * JZ4760 OST register definition
 * Copyright (C) 2010 Ingenic Semiconductor Co., Ltd.
 *
 * Author: whxu@ingenic.cn
 */

#ifndef __X100OST_H__
#define __X1000OST_H__

#define	OST_BASE	0xB2000000

/*
 * OST registers common define
 */


#define OST_OSTCCR_OFFSET	(0x0)
#define OST_OSTER_OFFSET	(0x4)
#define OST_OSTESR_OFFSET	(0x34)
#define OST_OSTECR_OFFSET	(0x38)
#define	OST_OSTCR_OFFSET	(0x8)
#define	OST_OSTFR_OFFSET	(0xc)
#define OST_OSTMR_OFFSET	(0x10)
#define OST_OST1DFR_OFFSET	(0x14)
#define OST_OST1CNT_OFFSET	(0x18)
#define	OST_OST2CNTH_OFFSET	(0x1c)
#define	OST_OST2CNTL_OFFSET	(0x20)
#define OST_OST2CNTHBUF_OFFSET	(0x24)

#define OST_OSTCCR	(OST_BASE + OST_OSTCCR_OFFSET)
#define OST_OSTER	(OST_BASE + OST_OSTER_OFFSET)
#define OST_OSTESR	(OST_BASE + OST_OSTESR_OFFSET)
#define OST_OSTECR	(OST_BASE + OST_OSTECR_OFFSET)
#define OST_OSTCR	(OST_BASE + OST_OSTCR_OFFSET)
#define OST_OSTFR	(OST_BASE + OST_OSTFR_OFFSET)
#define OST_OSTMR	(OST_BASE + OST_OSTMR_OFFSET)
#define OST_OST1DFR	(OST_BASE + OST_OST1DFR_OFFSET)
#define OST_OST1CNT	(OST_BASE + OST_OST1CNT_OFFSET)
#define OST_OST2CNTH	(OST_BASE + OST_OST2CNTH_OFFSET)
#define OST_OST2CNTL	(OST_BASE + OST_OST2CNTL_OFFSET)
#define OST_OST2CNTHBUF	(OST_BASE + OST_OST2CNTHBUF_OFFSET)

#define REG_OSTCCR	REG32(OST_OSTCCR)
#define REG_OSTER	REG32(OST_OSTER)
#define REG_OSTESR	REG32(OST_OSTESR)
#define REG_OSTECR	REG32(OST_OSTECR)
#define REG_OSTCR	REG32(OST_OSTCR)
#define	REG_OSTFR	REG32(OST_OSTFR)
#define REG_OSTMR	REG32(OST_OSTMR)
#define	REG_OST1DFR	REG32(OST_OST1DFR)
#define REG_OST1CNT	REG32(OST_OST1CNT)
#define REG_OST2CNTH	REG32(OST_OST2CNTH)
#define REG_0ST2CNTL	REG32(OST_OST2CNTL)
#define REG_OST2CNTHBUF	REG32(OST_OST2CNTHBUF)



#endif /* __X1000OST_H__ */
